### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by lxx59** [wentaoyuan/RoboPoint#2]
An interruption occurred when I downloaded object_ref 00,01,02 and merged them to extract.
![c7fadddd30735326ab9f7a69ae5cd32](https://github.com/user-attachments/assets/8979149e-7261-4b3a-aff1-499595b9ea57)
How can i do?

**Comment by jiafei1224** [comment]
try again and run this:
cat object_ref.tar.gz.part_* > object_ref.tar.gz
first
