### ISSUE TITLE
Dataset generation code

### ISSUE THREAD

**Issue by dohyun1411** [wentaoyuan/RoboPoint#3]
Hi,

Is there any plan to release the dataset generation code?

**Comment by jiafei1224** [comment]
Hi,

We cannot release the dataset generation code due to some IP issues, however the method to perform dataset generation is easily reproducible by following the paper.  Sorry about it.

**Comment by dohyun1411** [comment]
@jiafei1224 Can I ask which simulator you used?

**Comment by jiafei1224** [comment]
https://joss.theoj.org/papers/10.21105/joss.07561.pdf

Check out this paper for more details
