### ISSUE TITLE
Missing Images in VG_100K_2 Directory

### ISSUE THREAD

**Issue by ilileun** [wentaoyuan/RoboPoint#5]
![image](https://github.com/user-attachments/assets/c1f6d8f9-5742-493b-a923-712339a30915)

When preparing the dataset, I encountered missing images in the VG_100K_2 directory. Specifically:

- Total examples in JSON: 1431521
- Available examples: 1357759
- Missing examples: 73762

Example missing files:
- /images/VG_100K_2/51.jpg
- /images/VG_100K_2/52.jpg
- /images/VG_100K_2/53.jpg
- /images/VG_100K_2/54.jpg
- /images/VG_100K_2/55.jpg ....

Could you please provide guidance on how to obtain these missing images or update the dataset accordingly?

**Comment by dohyun1411** [comment]
Hi, how did you solve the issue?

**Comment by memmelma** [comment]
The huggingface dataset is missing `VG_100K_2`.

Download it from the [original source](https://cs.stanford.edu/people/rak248/VG_100K_2/images2.zip) and unzip it in the `images/` folder.

Reference: https://huggingface.co/datasets/ranjaykrishna/visual_genome/blob/65bc9e7e7353fff750326c9523e384701934e530/visual_genome.py#L54
